name: 'SteamSaleWatcher'
version: 0.0.1
description: Steam Sale Watcher. Saving money for all gamers.

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  bootstrap: "^3.3.4"
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter
- bootstrap:
    url: //maxcdn.bootstrapcdn.com/bootstrap/3.3.4
    version: 3.3.4